services:
  palworld-server:
    image: ghcr.io/pocketpairjp/palserver:v0.3.9.59545
    command:
      - -port=8211
      - -useperfthreads
      - -NoAsyncLoadingThread
      - -UseMultithreadForDS
    ports:
      - "8211:8211/udp"
    volumes:
      - ./Saved:/pal/Package/Pal/Saved
